package core.game.content.dialogue;

public enum DialogueType {
	TWO_OPTIONS_1,
	TWO_OPTIONS_2,
	THREE_OPTIONS_1,
	THREE_OPTIONS_2,
	THREE_OPTIONS_3,
	FOUR_OPTIONS_1,
	FOUR_OPTIONS_2,
	FOUR_OPTIONS_3,
	FOUR_OPTIONS_4,		
	FIVE_OPTIONS_1,
	FIVE_OPTIONS_2,
	FIVE_OPTIONS_3,
	FIVE_OPTIONS_4,
	FIVE_OPTIONS_5
}	
